# Generated by Django 4.1.5 on 2023-01-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0003_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='coupen_request',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='Pending', max_length=50),
        ),
    ]
