# Generated by Django 4.1.5 on 2023-01-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0005_remove_wallet_user_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
