# Generated by Django 4.1.5 on 2023-01-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0006_recharge_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='remaining_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
