# Generated by Django 4.1.5 on 2023-01-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0010_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
