# Generated by Django 4.1.5 on 2023-01-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0011_alter_withdraw_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='withdraw_request',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='Pending', max_length=50),
        ),
    ]
